# Generated by Django 3.1.5 on 2021-11-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hon_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="password",
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="apikey",
            name="username",
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="cookie",
            field=models.CharField(max_length=127),
        ),
    ]
