# Generated by Django 3.1.5 on 2021-01-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                ("hero_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128, null=True)),
                ("code", models.CharField(max_length=128, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, null=True)),
                ("code", models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
    ]
