# Generated by Django 3.1.5 on 2021-01-18 16:54

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("account_id", models.IntegerField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(max_length=128)),
                ("super_id", models.IntegerField()),
                ("games_played", models.IntegerField()),
                ("total_games_played", models.IntegerField()),
                ("create_date", models.DateField()),
                ("last_activity", models.DateField()),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
