# Generated by Django 3.1.5 on 2021-02-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210123_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='clan_tag',
            field=models.CharField(db_index=True, max_length=128, null=True),
        ),
    ]
