# Generated by Django 3.1.5 on 2021-02-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210209_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='season_games_played',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='season_losses',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='season_wins',
            field=models.IntegerField(null=True),
        ),
    ]
