version: 0.0
os: linux
files:
  - source: /
    destination: /honstats
hooks:
  AfterInstall:
    - location: .aws/scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: .aws/scripts/application_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: .aws/scripts/application_stop.sh
      timeout: 300
      runas: root