version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - python3 -m venv venv
      - . venv/bin/activate
      - pip install -r requirements.txt
      - mkdir test-reports
  build:
    commands:
      - echo Build started
  post_build:
    commands:
      - echo Build completed on `date`\
artifacts:
  files:
    - '**/*'