version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - yum install python3
      - yum install python3-venv
      - python3 -m venv test_venv
      - . test_venv/bin/activate
      - pip install --upgrade pip
      - pip install .
      - pip install -r requirements.txt
      - mkdir test-reports
  build:
    commands:
      - echo Build started
  post_build:
    commands:
      - echo Build completed on `date`