# Generated by Django 3.1.5 on 2021-01-22 22:37

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game_data", "0001_initial"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("match_id", models.IntegerField(primary_key=True, serialize=False)),
                ("match_date", models.DateField()),
                ("match_name", models.CharField(max_length=127)),
                ("replay_log_url", models.CharField(max_length=511)),
                (
                    "winning_team",
                    models.TextField(
                        choices=[("0", "Empty"), ("1", "Radiant"), ("2", "Dire")],
                        default="0",
                        max_length=1,
                    ),
                ),
                (
                    "parsed_level",
                    models.TextField(
                        choices=[("1", "FETCHED"), ("2", "API"), ("3", "REPLAY")],
                        default="1",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "team",
                    models.TextField(
                        choices=[("0", "Empty"), ("1", "Radiant"), ("2", "Dire")],
                        default="0",
                        max_length=1,
                    ),
                ),
                ("position", models.TextField(max_length=1, null=True)),
                ("level", models.IntegerField(null=True)),
                ("hero_kills", models.IntegerField(null=True)),
                ("deaths", models.IntegerField(null=True)),
                ("kicked", models.BooleanField(default=False)),
                ("hero_assists", models.IntegerField(null=True)),
                ("networth", models.IntegerField(null=True)),
                ("hero_damage", models.IntegerField(null=True)),
                ("lasthits", models.IntegerField(null=True)),
                ("denies", models.IntegerField(null=True)),
                ("wards", models.IntegerField(null=True)),
                ("mmr_before", models.FloatField(null=True)),
                ("mmr_after", models.FloatField(null=True)),
                ("final_items", models.JSONField(default=dict)),
                ("gpm", models.FloatField(null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="matches",
                        to="account.account",
                    ),
                ),
                (
                    "hero",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="game_data.hero",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="match.match"
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
