# Generated by Django 3.1.5 on 2021-01-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"ordering": ["-match_id"]},
        ),
        migrations.AddField(
            model_name="match",
            name="duration",
            field=models.IntegerField(null=True),
        ),
    ]
