# Generated by Django 3.1.5 on 2021-01-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20210124_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='networth_diff',
            field=models.JSONField(null=True),
        ),
    ]
