# Generated by Django 3.1.5 on 2021-01-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0006_match_exp_diff"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="networth_time",
            field=models.JSONField(null=True),
        ),
    ]
