# Generated by Django 3.1.5 on 2021-01-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0007_player_networth_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="item_times",
            field=models.JSONField(null=True),
        ),
    ]
