# Generated by Django 3.1.5 on 2021-11-07 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_auto_20210209_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.match'),
        ),
    ]
