# Generated by Django 3.1.5 on 2021-11-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0011_auto_20211107_2335"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="dewards",
            field=models.IntegerField(null=True),
        ),
    ]
