# Generated by Django 3.1.5 on 2021-11-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0012_player_dewards"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="obs_wards",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="rev_wards",
            field=models.IntegerField(null=True),
        ),
    ]
