# Generated by Django 3.1.5 on 2021-11-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0013_auto_20211110_2059"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="uncountered_wards",
            field=models.IntegerField(null=True),
        ),
    ]
