# Generated by Django 3.1.5 on 2021-11-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0015_match_game_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="concede",
            field=models.BooleanField(default=False),
        ),
    ]
