# Generated by Django 3.1.5 on 2021-12-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("match", "0017_match_boss_kills"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="last_attempt_time",
            field=models.DateTimeField(null=True),
        ),
    ]
